---

- name: create folder
  hosts: fedora
  become: true
  tasks:

  - name: Create folder
    file:
      path: /tmp/newfolder
      state: directory
 
- name: load file
  hosts: fedora
  become: true
  tasks:

  - name: downloadfile
    get_url:
      url: "https://downloads.apache.org/kafka/3.4.0/kafka-3.4.0-src.tgz"
      dest: /tmp/newfolder/
    register: download_status

- name: unzip archive
  hosts: fedora
  become: true
  tasks:

  - name: unzip archive
    unarchive:
      src: "/tmp/newfolder/kafka-3.4.0-src.tgz"
      dest: /tmp/newfolder
#      remote_src: yes
      copy: no
