---
# tasks file for apache

- name: download and install apache
  apt:
    name: apache2
    state: present

#- name: configure index.html
#  template:
#    src: templates/index.html.j2
#    dest: /var/wwww/html/index.html
#  vars:
#    cpu: "{{ ansible_process_count }}"
#    ram: "{{ ansible_memtotal_mb }} MB"


- name: Add index page
  template:
    src: "index.html.j2"
    dest: "/var/www/html/index.html"
    owner: root
    group: root
    mode: 0755


- name: restart apache2 service
  service:
    name: apache2
    state: restarted

- name: open port 80
  become: true
  ufw:
    rule: allow
    port: 80

- name: add apache into autostart
  become: true
  systemd:
    name: apache2
    enabled: yes
