---

- name: change system greeting
  hosts: fedora
  become: true
  tasks:

  - name: changed greeting
    copy: 
      dest: /etc/motd
      content: |
       Welcome to our system {{ansible_facts.all_ipv4_addresses[0]}}
       This is a secure and reliable platform for all your computing needs.
       Good day for admin of {{ansible_facts.hostname}}

  - name: restart ssh service
    become: true
    service:
      name: sshd
      state: restarted      
